version: '3'

services:
  web:
    build: .
    command: python -u app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: deneme
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_conteiner
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
